org 1800h
START:
	jr MAIN
ds 0x1838-$,0
;org 1838h
INTERRUPT:
	PUSH A
	PUSH F
	IN A, (O1H)
	AND A, 0FH
	LD B, A
	OUT (O1H), A
	POP F
	POP A
	EI
	RETI
ds 0x1860-$,0
;org 1860h
MAIN:
	IN A, (01H) ; ŁADOWANIE Z WEJSCIA
	AND A, 0FH
	LD B, A
	OUT (O1H), A ; ODSWIEŻENIE LED
	LD D, 200
	IM 1
	EI	
	IN A, (01H)
	BIT 4, A ; PRZYCISK CLK
	JR NZ, STAN_HIGH ; JESLI CLK WYSOKI
STAN_LOW:
	IN A, (01H)
	BIT 4, A ; PRZYCISK CLK	
	JR Z, STAN_LOW
	LD C, D
STAN_RISING_EDGE:
	IN A, (01H)
	BIT 4, A ; PRZYCISK CLK	
	JR Z, STAN_LOW
	DEC C
	JR NZ, STAN_RISING_EDGE
	; POPRAWNE ZBOCZE NARASTAJACE
	DEC B
	OUT (O1H), B	
STAN_HIGH:
	IN A, (01H)
	BIT 4, A ; PRZYCISK CLK		
	JR NZ, STAN_HIGH
	LD C, D
STAN_FALLING_EDGE:
	IN A, (01H)
	BIT 4, A ; PRZYCISK CLK	
	JR NZ, STAN_HIGH
	DEC C
	JR NZ, STAN_FALLING_EDGE
	; POPRAWNE ZBOCZE OPADAJACE
	JR STAN_LOW